#Inserção de dado. . .
print("Seu nome:")
MyName = str(input())
print("Sua idade:")
MyAge = int(input())
print("Sua altura:")
MyHeigh = float(input())
print("Seu peso:")
MyWeight = float(input())
print("Seu hobby:")
MyHooby = str(input())
print("Sua profissão:")
MyWork = str(input())
print("Nome do grupo:")
MyNameGroup = str(input())
print("Número que te repressenta:")
MyNumber = int(input())
print("Lugar Favorito:")
MyFavoritePlace = str(input())
print("Bebida Favorita:")
MyFavoriteDrink = str(input())

#Exibição do conteúdo das variáveis. . .
print("Meu nome é", MyName)
print("Minha idade é", MyAge)
print("Minha altura é", MyHeigh)
print("Meu peso é", MyWeight)
print("Meu hobby é", MyHooby)
print("Minha profissão é", MyWork)
print("O nome do meu grupo é", MyNameGroup)
print("O número que me representa é", MyNumber)
print("Meu lugar favorito é", MyFavoritePlace)
print("Minha bebida favorita é", MyFavoriteDrink)
